version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres 
    volumes:
      - ./:/usr/src/app:ro 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=998d0879fdf1b9f5fdfdcdd96bd9b9fbd0718e39178c3fedcb5a3152cd923d4b
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data  

volumes:
  postgres-db:
    
